"""kickoffs: templates, kickoff, questions, answers; project waiting_on_client status

Revision ID: 07a5cf5d5bed
Revises: c9d3f5a1e246
Create Date: 2026-09-27 13:56:52.096718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a5cf5d5bed'
down_revision: Union[str, Sequence[str], None] = 'c9d3f5a1e246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kickoff_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'name', name='uq_kickoff_templates_agency_id_name')
    )
    op.create_index(op.f('ix_kickoff_templates_agency_id'), 'kickoff_templates', ['agency_id'], unique=False)
    op.create_table('kickoff_template_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['kickoff_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kickoff_template_questions_template_id'), 'kickoff_template_questions', ['template_id'], unique=False)
    op.create_table('kickoffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('intro_message', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_nudged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['agency_clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kickoffs_agency_id'), 'kickoffs', ['agency_id'], unique=False)
    op.create_index(op.f('ix_kickoffs_client_id'), 'kickoffs', ['client_id'], unique=False)
    op.create_index(op.f('ix_kickoffs_project_id'), 'kickoffs', ['project_id'], unique=True)
    op.create_table('kickoff_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kickoff_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['kickoff_id'], ['kickoffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kickoff_questions_kickoff_id'), 'kickoff_questions', ['kickoff_id'], unique=False)
    op.create_table('kickoff_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kickoff_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answered_by_id', sa.Uuid(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('selected_options', sa.Text(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['answered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['project_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kickoff_id'], ['kickoffs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['kickoff_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', name='uq_kickoff_answers_question_id')
    )
    op.create_index(op.f('ix_kickoff_answers_kickoff_id'), 'kickoff_answers', ['kickoff_id'], unique=False)
    op.create_index(op.f('ix_kickoff_answers_question_id'), 'kickoff_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kickoff_answers_question_id'), table_name='kickoff_answers')
    op.drop_index(op.f('ix_kickoff_answers_kickoff_id'), table_name='kickoff_answers')
    op.drop_table('kickoff_answers')
    op.drop_index(op.f('ix_kickoff_questions_kickoff_id'), table_name='kickoff_questions')
    op.drop_table('kickoff_questions')
    op.drop_index(op.f('ix_kickoffs_project_id'), table_name='kickoffs')
    op.drop_index(op.f('ix_kickoffs_client_id'), table_name='kickoffs')
    op.drop_index(op.f('ix_kickoffs_agency_id'), table_name='kickoffs')
    op.drop_table('kickoffs')
    op.drop_index(op.f('ix_kickoff_template_questions_template_id'), table_name='kickoff_template_questions')
    op.drop_table('kickoff_template_questions')
    op.drop_index(op.f('ix_kickoff_templates_agency_id'), table_name='kickoff_templates')
    op.drop_table('kickoff_templates')
    # ### end Alembic commands ###
