"""dashboard briefings cache table

Revision ID: 1f3b7144b50c
Revises: 5eabbb21669b
Create Date: 2026-09-11 15:39:55.282956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3b7144b50c'
down_revision: Union[str, Sequence[str], None] = '5eabbb21669b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_briefings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'user_id', 'briefing_date', name='uq_dashboard_briefings_agency_user_date')
    )
    op.create_index(op.f('ix_dashboard_briefings_agency_id'), 'dashboard_briefings', ['agency_id'], unique=False)
    op.create_index(op.f('ix_dashboard_briefings_user_id'), 'dashboard_briefings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_briefings_user_id'), table_name='dashboard_briefings')
    op.drop_index(op.f('ix_dashboard_briefings_agency_id'), table_name='dashboard_briefings')
    op.drop_table('dashboard_briefings')
    # ### end Alembic commands ###
