"""proposals, time_tracking, recurring invoices

Revision ID: 59d8c24f0a6a
Revises: b5e3e7e0d2b5
Create Date: 2026-09-22 13:57:52.637955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d8c24f0a6a'
down_revision: Union[str, Sequence[str], None] = 'b5e3e7e0d2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tax_rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['agency_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_agency_id'), 'proposals', ['agency_id'], unique=False)
    op.create_index(op.f('ix_proposals_client_id'), 'proposals', ['client_id'], unique=False)
    op.create_index(op.f('ix_proposals_lead_id'), 'proposals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_proposals_share_token'), 'proposals', ['share_token'], unique=True)
    op.create_table('proposal_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_line_items_proposal_id'), 'proposal_line_items', ['proposal_id'], unique=False)
    op.create_table('proposal_signatures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('signer_name', sa.String(length=255), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=False),
    sa.Column('signature_text', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_signatures_proposal_id'), 'proposal_signatures', ['proposal_id'], unique=True)
    op.create_table('recurring_invoice_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=4096), nullable=True),
    sa.Column('payment_instructions', sa.String(length=2048), nullable=True),
    sa.Column('auto_issue', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_generated_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['agency_clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_generated_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_invoice_schedules_agency_id'), 'recurring_invoice_schedules', ['agency_id'], unique=False)
    op.create_index(op.f('ix_recurring_invoice_schedules_client_id'), 'recurring_invoice_schedules', ['client_id'], unique=False)
    op.create_index(op.f('ix_recurring_invoice_schedules_next_run_date'), 'recurring_invoice_schedules', ['next_run_date'], unique=False)
    op.create_index(op.f('ix_recurring_invoice_schedules_project_id'), 'recurring_invoice_schedules', ['project_id'], unique=False)
    op.create_table('recurring_invoice_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['recurring_invoice_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_invoice_line_items_schedule_id'), 'recurring_invoice_line_items', ['schedule_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('hourly_rate_cents', sa.Integer(), nullable=True),
    sa.Column('invoice_line_item_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_line_item_id'], ['invoice_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_agency_id'), 'time_entries', ['agency_id'], unique=False)
    op.create_index(op.f('ix_time_entries_invoice_line_item_id'), 'time_entries', ['invoice_line_item_id'], unique=False)
    op.create_index(op.f('ix_time_entries_project_id'), 'time_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_started_at'), 'time_entries', ['started_at'], unique=False)
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('default_hourly_rate_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'default_hourly_rate_cents')
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_started_at'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_project_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_invoice_line_item_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_agency_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_recurring_invoice_line_items_schedule_id'), table_name='recurring_invoice_line_items')
    op.drop_table('recurring_invoice_line_items')
    op.drop_index(op.f('ix_recurring_invoice_schedules_project_id'), table_name='recurring_invoice_schedules')
    op.drop_index(op.f('ix_recurring_invoice_schedules_next_run_date'), table_name='recurring_invoice_schedules')
    op.drop_index(op.f('ix_recurring_invoice_schedules_client_id'), table_name='recurring_invoice_schedules')
    op.drop_index(op.f('ix_recurring_invoice_schedules_agency_id'), table_name='recurring_invoice_schedules')
    op.drop_table('recurring_invoice_schedules')
    op.drop_index(op.f('ix_proposal_signatures_proposal_id'), table_name='proposal_signatures')
    op.drop_table('proposal_signatures')
    op.drop_index(op.f('ix_proposal_line_items_proposal_id'), table_name='proposal_line_items')
    op.drop_table('proposal_line_items')
    op.drop_index(op.f('ix_proposals_share_token'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_lead_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_client_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_agency_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
